### PR TITLE
fix(preview): disallow folders with illegal characters

### LINKED ISSUE #266: [preview] disallow previews from folders with spaces
Port from https://github.com/adobe/helix-sidekick-extension/pull/807

### PR DESCRIPTION
**Pull request by rofe**
Fix #266

### CODE REVIEW

File: src/extension/app/plugins/preview/preview.js [hunk 1]
```diff
@@ -45,6 +45,20 @@ export function createPreviewPlugin(appStore) {
...
         const { location } = appStore;
         const status = await appStore.fetchStatus(false, true, true);
+        if (status.edit?.illegalPath) {
+          appStore.showToast(
+            appStore.i18n('bulk_error_illegal_file_name')
+              .replace('$1', status.webPath),
+            'warning',
+            undefined,
+            undefined,
+            undefined,
```
Comment (dylandepass) [inline src/extension/app/plugins/preview/preview.js:55]: 🥲

**Review by dylandepass — APPROVED** [review]
