### PR TITLE
fix(json): table header and body can be mismatched

### LINKED ISSUE #411: [json] header/body misalignments in table of json view
the json table renderer assumes that all rows have the same properties/keys in the same order. this is not always the case, for example, when only part of a query index gets updated after an index definiotion change.

### PR DESCRIPTION
**Pull request by rofe**
Fix #411

### CODE REVIEW

File: src/extension/views/json/json.js [hunk 1]
```diff
@@ -235,13 +261,13 @@ export class JSONView extends LitElement {
...
-      const headers = rows[0];
-      const headHTML = Object.keys(headers).reduce((acc, key) => `${acc}<sp-table-head-cell sortable sort-direction="desc" sort-key=${key}>${key.charAt(0).toUpperCase() + key.slice(1)}</sp-table-head-cell>`, '');
+      const headers = this.getHeaders(rows);
+      const headHTML = headers.reduce((acc, key) => `${acc}<sp-table-head-cell sortable sort-direction="desc" sort-key=${key}>${key.charAt(0).toUpperCase() + key.slice(1)}</sp-table-head-cell>`, '');
       const head = document.createElement('sp-table-head');
       head.insertAdjacentHTML('beforeend', headHTML);
       table.appendChild(head);
 
-      table.items = rows;
+      table.items = this.sortRows(rows, headers);
```
Comment (tripodsan) [inline src/extension/views/json/json.js:270]: why do you sort the rows here? isn't this wrong?

File: src/extension/views/json/json.js [hunk 2]
```diff
@@ -220,6 +220,32 @@ export class JSONView extends LitElement {
...
   }
 
+  /**
+   * Finds the row with the most keys and returns key names as headers.
+   * @param {Object[]} rows The rows
+   * @returns {string[]} The header names
+   */
+  getHeaders(rows) {
+    const sortedRows = rows.sort((a, b) => Object.keys(b).length - Object.keys(a).length);
+    return Object.keys(sortedRows[0]);
```
Comment (tripodsan) [inline src/extension/views/json/json.js:230]: I think it would be better to iterate over all rows, and build the list of all possible keys. probably similarly expensive than sorting with this expensive comparator ;-)

File: src/extension/views/json/json.js [hunk 3]
```diff
@@ -220,6 +220,32 @@ export class JSONView extends LitElement {
...
+  }
+
+  /**
+   * Sorts all rows based on the headers
+   * @param {Object[]} rows The rows
+   * @param {string[]} headers The header names
+   * @returns {Object[]} The sorted rows
+   */
+  sortRows(rows, headers) {
```
Comment (tripodsan) [inline src/extension/views/json/json.js:239]: misleading name. better: `matchColsToHeaders()`  ??

File: src/extension/views/json/json.js (hunk 2 above)
Comment (rofe) [reply src/extension/views/json/json.js]: Now using `columns` from payload instead

File: src/extension/views/json/json.js (hunk 3 above)
Comment (rofe) [reply src/extension/views/json/json.js]: Actually, `sortColumns` would be more accurate :)

**Review by tripodsan — APPROVED** [review]

**Comment by dylandepass** [comment]
@rofe This also fixes https://github.com/adobe/aem-sidekick/issues/123

I think just showing the the JSON with empty data as we are doing now is a good fix, wdyt?
