### PR TITLE
fix: instrument user agent

### LINKED ISSUE #595: Instrument user agent
Append ` AEMSidekick/{version}` to the `user-agent` header when communicating with the admin API.

### PR DESCRIPTION
**Pull request by rofe**
Fix #595

### CODE REVIEW

File: src/extension/auth.js [hunk 1]
```diff
@@ -211,3 +211,32 @@ export async function setAuthToken(
     await configureAuthAndCorsHeaders();
   }
 }
+
+/**
+ * Adds the sidekick version to the user agent for requests to the Admin API.
+ * @returns {Promise<void>}
+ */
+export async function updateUserAgent() {
+  const userAgent = `${navigator.userAgent} Sidekick/${chrome.runtime.getManifest().version}`;
```
Comment (tripodsan) [inline src/extension/auth.js:220]: maybe `AEMSidekick`  ?

```suggestion
  const userAgent = `${navigator.userAgent} AEMSidekick/${chrome.runtime.getManifest().version}`;
```

**Review by dylandepass — APPROVED** [review]
