### PR TITLE
fix: switch to rum click events

### LINKED ISSUE #171: Add `sidekick:loaded` rum checkpoint

### LINKED ISSUE #214: Switch to click-based usage monitoring
Custom checkpoints have an expiry date in RUM.

### PR DESCRIPTION
**Pull request by dylandepass**
Switch to click tracking instead if checkpoints for rum collection.

I'm using 'sidekick' as the source element for all interactions.

Fixes #171
Fixes #214 

### Loaded

- [x] Tests

```js
sampleRUM('click', {
  source: 'sidekick',
  target: `loaded:${browser}`,
});
```

> Where `browser` is one of ['edge', 'opera', 'samsumg', 'chrome', 'safari', 'firefox']

### Environment Switch

- [x] Tests

```js
sampleRUM('click', {
  source: 'sidekick',
  target: `env-switched:${value}`,
});
```

> Where value is one of ['edit'. 'preview', 'live', 'prod']

### Palette Opened

- [x] Tests

```js
sampleRUM('click', {
  source: 'sidekick',
  target: 'palette-opened',
});
```

### Palette Closed

- [x] Tests

```js
sampleRUM('click', {
  source: 'sidekick',
  target: 'palette-closed',
});
```

### Open help

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'help-opened' 
});
```

### Project added

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'project-added' 
});
```

### Project removed

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'project-removed' 
});
```

### Operations

- [x] Preview test
- [x] Updated test
- [x] Publish test
- [x] Unpublished test
- [x] Deleted test

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: ${operation}
});
```

> Where `operation` is one of ['updated', 'previewed', 'published', 'unpublished', 'deleted'];
> These events are also dispatched from the sidekick element.

### Login

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'logged-in'
});
```

> This events is also dispatched from the sidekick element.

### Logout

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'logged-out'
});
```

> This events is also dispatched from the sidekick element.

### Sidekick Shown

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'shown'
});
```

### Sidekick Hidden

- [x] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'hidden'
});
```

> This events is also dispatched from the sidekick element if closed via the menu in the sidekick. Show/hide events from the background script (via the context menu) are not dispatched from the sidekick element.

### Context Menu events

- [x] addRemoveProject tests
- [x] enableDisableProject tests
- [x] openViewDocSource tests
- [x] importProjects tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: `context-menu:${id}`
});
```

> Where `id` is one of ['addRemoveProject', 'enableDisableProject', 'openViewDocSource', 'importProjects'];

### JSON View Filter

- [ ] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'jsonview:filtered'
});
```

### JSON View Switch Tab

- [ ] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'jsonview:tab-switched'
});
```

### JSON View Close

- [ ] Tests

```js
sampleRUM('click', { 
  source: 'sidekick', 
  target: 'jsonview:closed'
});
```

### CODE REVIEW

File: src/extension/app/plugins/delete/delete.js [hunk 1]
```diff
@@ -77,6 +78,7 @@ export function createDeletePlugin(appStore) {
               actionCallback,
               appStore.i18n('reload'),
             );
+            appStore.fireEvent(EXTERNAL_EVENTS.RESOURCE_DELETED);
```
Comment (dylandepass) [inline src/extension/app/plugins/delete/delete.js:81]: Changed all plugins to call `fireEvent` directly from the plugin vs in the appStore. This was done to simplify testing.

File: src/extension/app/store/app.js [hunk 2]
```diff
@@ -688,26 +688,20 @@ export class AppStore {
         detail: { data },
       }));
       const userEvents = [
-        'shown',
```
Comment (dylandepass) [inline src/extension/app/store/app.js:691]: Removed unused events that carried over from the old extension.

File: src/extension/app/store/app.js [hunk 3]
```diff
@@ -688,26 +688,20 @@ export class AppStore {
...
         'hidden',
         'updated',
         'previewed',
         'published',
         'unpublished',
         'deleted',
-        'envswitched',
```
Comment (dylandepass) [inline src/extension/app/store/app.js:698]: Now dispatched from the env-switcher plugin

File: src/extension/app/aem-sidekick.js [hunk 4]
```diff
@@ -41,6 +42,13 @@ export class AEMSidekick extends LitElement {
 
   async loadContext(config) {
     await this.appStore.loadContext(this, config);
+
+    const browser = detectBrowser(navigator.userAgent);
+    this.appStore.sampleRUM('click', {
+      source: 'sidekick',
+      target: `loaded:${browser}`,
```
Comment (dylandepass) [inline src/extension/app/aem-sidekick.js:49]: Dropped `platform` since we should already get this via RUM.

Comment (rofe) [reply src/extension/app/aem-sidekick.js:49]: What about the browser then? We should probably not try to detect this twice and differently.

Comment (dylandepass) [reply src/extension/app/aem-sidekick.js:49]: I didn't see anything in the RUM explorer detailing the browser. Could have missed it though. Maybe @trieloff can confirm if this is needed or not.

File: src/extension/app/components/plugin/env-switcher/env-switcher.js [hunk 5]
```diff
@@ -313,6 +313,11 @@ export class EnvironmentSwitcher extends ConnectedElement {
 
     this.appStore.switchEnv(value, openNewTab);
     picker.value = this.currentEnv;
+
+    this.appStore.sampleRUM('click', {
+      source: 'sidekick',
+      target: `switch-env:${value}`,
```
Comment (rofe) [inline src/extension/app/components/plugin/env-switcher/env-switcher.js:319]: should we stick with past tense, i.e. `envswitched`?

File: src/extension/app/plugins/reload/reload.js [hunk 6]
```diff
@@ -36,6 +37,7 @@ export function createReloadPlugin(appStore) {
         const res = await appStore.update();
         if (res) {
           appStore.showToast(appStore.i18n('reload_success'), 'positive');
+          appStore.fireEvent(EXTERNAL_EVENTS.RESOURCE_UPDATED);
```
Comment (rofe) [inline src/extension/app/plugins/reload/reload.js:40]: I'm wondering if we should start distinguishing between previewed from the editor vs reloaded?

One way we could do this to keep a single target for `updated` would be to add the environment to `sidekick` in the source as a suffix.

File: src/extension/app/store/app.js (hunk 2 above)
Comment (rofe) [reply src/extension/app/store/app.js:691]: I think this would be a good time to consolidate to a single list of event names in `EXTERNAL_EVENTS` instead of duplicating them here.

File: src/extension/display.js [hunk 7]
```diff
@@ -30,6 +30,14 @@ export async function setDisplay(display) {
   await setConfig('local', {
     display,
   });
+
+  const mod = await import(chrome.runtime.getURL('utils/rum.js'));
+  const { default: sampleRUM } = mod;
+
+  sampleRUM('click', {
+    source: 'sidekick',
+    target: `${display ? 'shown' : 'hidden'}`,
```
Comment (rofe) [inline src/extension/display.js:39]: Move these to `EXTERNAL_EVENTS`?

File: src/extension/views/doc-source/js/ui.js [hunk 8]
```diff
@@ -237,8 +237,9 @@ const load = async () => {
       copyButton.classList.remove('copied');
     }, 2000);
 
-    sampleRUM('sidekick:copydocsource', {
-      source: tab.url,
+    sampleRUM('click', {
+      source: 'sidekick',
+      target: 'copydocsource',
```
Comment (rofe) [inline src/extension/views/doc-source/js/ui.js:242]: Should we change this to past tense to match the others, e.g. `doc-source-opened`?

File: src/extension/views/doc-source/js/ui.js [hunk 9]
```diff
@@ -247,8 +248,9 @@ const load = async () => {
     sendMessage({ fct: 'setMain', params: { html: htmlEditionToSource() } });
   }, 500));
 
-  sampleRUM('sidekick:viewdocsource', {
-    source: tab.url,
+  sampleRUM('click', {
+    source: 'sidekick',
+    target: 'viewdocsource',
```
Comment (rofe) [inline src/extension/views/doc-source/js/ui.js:253]: Should we change this to past tense to match the others, e.g. `doc-source-copied`?

File: src/extension/app/components/plugin/env-switcher/env-switcher.js (hunk 5 above)
Comment (dylandepass) [reply src/extension/app/components/plugin/env-switcher/env-switcher.js:319]: Makes sense, will switch to `env-switched:${value}`

File: src/extension/app/plugins/reload/reload.js (hunk 6 above)
Comment (dylandepass) [reply src/extension/app/plugins/reload/reload.js:40]: Agreed, this change in logic should already be implemented in this PR.

When previewing we dispatch `EXTERNAL_EVENTS.RESOURCE_PREVIEWED`

When reloading we dispatch `EXTERNAL_EVENTS.RESOURCE_UPDATED` 

Previously we were dispatching [PREVIEWED](https://github.com/adobe/aem-sidekick/pull/258/files#diff-2232b3a8d76d8fdfb8c5d8f3d8fe25a9fc392b09dce95767f015a1c382061104L885) for both.

File: src/extension/display.js (hunk 7 above)
Comment (dylandepass) [reply src/extension/display.js:39]: Just a clarification. By external events do we mean events dispatched by the custom element? Currently only `hidden` is dispatched from the element.

Comment (rofe) [reply src/extension/display.js:39]: Right, I guess I got events and checkpoints confused.

File: src/extension/app/components/plugin/plugin-action-bar.js [hunk 10]
```diff
@@ -285,13 +284,13 @@ export class PluginActionBar extends ConnectedElement {
     menu.removeAttribute('open');
 
     if (value === 'open-help') {
-      sampleRUM('sidekick:open-help');
+      this.appStore.sampleRUM('click', { source: 'sidekick', target: 'open-help' });
```
Comment (rofe) [inline src/extension/app/components/plugin/plugin-action-bar.js:287]: `help-opened`?

File: src/extension/views/json/json.js [hunk 11]
```diff
@@ -378,7 +378,10 @@ export class JSONView extends LitElement {
    * RUM tracking for the filter
    */
   trackFilterRUM() {
-    sampleRUM('sidekick:jsonview:filter');
+    sampleRUM('click', {
+      source: 'sidekick',
+      target: 'jsonview:filter',
```
Comment (rofe) [inline src/extension/views/json/json.js:383]: `jsonview:filtered`?

File: src/extension/views/json/json.js [hunk 12]
```diff
@@ -425,7 +428,10 @@ export class JSONView extends LitElement {
   async onSelectionChange() {
     const actionGroup = await this.actionGroup;
     this.selectedTabIndex = parseInt(actionGroup.selected[0], 10);
-    sampleRUM('sidekick:jsonview:switch-tab');
+    sampleRUM('click', {
+      source: 'sidekick',
+      target: 'jsonview:switch-tab',
```
Comment (rofe) [inline src/extension/views/json/json.js:433]: `jsonview:tab-switched`?

File: src/extension/views/json/json.js [hunk 13]
```diff
@@ -435,7 +441,10 @@ export class JSONView extends LitElement {
     const customEventDetail = { detail: { event: 'hlx-close-view' } };
     window.parent.postMessage(customEventDetail, '*');
     if (trackRum) {
-      sampleRUM('sidekick:jsonview:close');
+      sampleRUM('click', {
+        source: 'sidekick',
+        target: 'jsonview:close',
```
Comment (rofe) [inline src/extension/views/json/json.js:446]: `jsonview:closed`?

**Review by rofe — COMMENTED** [review]
More nitpicking 😁

File: src/extension/views/doc-source/js/ui.js [hunk 14]
```diff
@@ -247,8 +248,9 @@ const load = async () => {
     sendMessage({ fct: 'setMain', params: { html: htmlEditionToSource() } });
   }, 500));
 
-  sampleRUM('sidekick:viewdocsource', {
-    source: tab.url,
+  sampleRUM('click', {
+    source: 'sidekick',
+    target: 'doc-source-opened',
```
Comment (rofe) [inline src/extension/views/doc-source/js/ui.js:253]: I think this one would duplicate `context-menu:openViewDocSource` and could be removed, unless there is another way to open this view.

Comment (dylandepass) [reply src/extension/views/doc-source/js/ui.js:253]: True, we are also in this weird place now where `openViewDocSource ` and similar are the only targets where the casing is `camelCase`.

Comment (rofe) [reply src/extension/views/doc-source/js/ui.js]: Right... I'd be in favor of changing the format of context menu item IDs to use hyphens, at least for their RUM targets. But I think it would be a little odd to change the IDs to past tense just to match the event name standard. Wdyt?

File: src/extension/app/aem-sidekick.js (hunk 4 above)
Comment (trieloff) [reply src/extension/app/aem-sidekick.js:49]: We don't do browser detection as fine-grained as you do here

**Review by trieloff — APPROVED** [review]

**Review by rofe — APPROVED** [review]
