### PR TITLE
fix: prevent popovers from auto-closing on SharePoint viewer pages (#…

### LINKED ISSUE #669: Popovers get auto-closed on SharePoint viewer URLs
On SharePoint viewer URLs (e.g. PDFs, images), the sidekick popeovers (environment switcher, plugin menu, sidekick menu) all get auto-closed right after opening. 

Workaround: keep mouse button pressed (`mousedown`), move cursor to the desired menu item, then let go (`mouseup`) to select it.

### PR DESCRIPTION
**Pull request by rofe**
Fix #669

### CODE REVIEW

File: src/extension/app/components/action-bar/picker/picker.js [hunk 1]
```diff
@@ -145,7 +154,7 @@ export class Picker extends SPPicker {
             .offset=${0}
             .open=${this.open && this.dependencyManager.loaded}
             .placement=${this.isMobile.matches ? undefined : this.placement}
-            .type=${this.isMobile.matches ? 'modal' : 'auto'}
+            .type=${this.isMobile.matches ? 'modal' : 'manual'}
```
Comment (rofe) [inline src/extension/app/components/action-bar/picker/picker.js:157]: This being set to auto was the root cause for the auto-close issue. Changing it to manual requires explicit close handling, hence the pointerdown event listeners in `aem-sidekick`.

**Review by dylandepass — APPROVED** [review]
