### PR TITLE
fix(json): arabic and hebrew displayed ltr

### LINKED ISSUE #568: [JSON view] text direction is always LTR
Text cells with characters intended for RTL display are always displayed LTR.

We could add a check for RTL characters and switch text direction if necessary:
```js
/[\u0590-\u06FF]/.test(string)
```
[source](https://stackoverflow.com/questions/12006095/javascript-how-to-check-if-character-is-rtl)

### PR DESCRIPTION
**Pull request by rofe**
Fix #568

### CODE REVIEW

File: src/extension/views/json/json.js [hunk 1]
```diff
@@ -352,7 +353,7 @@ export class JSONView extends LitElement {
         valueContainer.classList.add('number');
         valueContainer.textContent = value;
       }
-    } else if (/\/^\/[a-z0-9]+$\/i/.test(value) || value.startsWith('http')) {
+    } else if (/^\/[a-z0-9]+/i.test(value) || value.startsWith('http')) {
```
Comment (rofe) [inline src/extension/views/json/json.js:356]: Fixes a regression introduced back in #432 which prevented links and linked images from being rendered as expected.

**Review by dylandepass — APPROVED** [review]
